/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FileUploadController: typeof import('./src/components/FileUploadController.vue')['default']
    IconCodiconDebugPause: typeof import('~icons/codicon/debug-pause')['default']
    IconCodiconDebugRestart: typeof import('~icons/codicon/debug-restart')['default']
    IconCodiconDebugStart: typeof import('~icons/codicon/debug-start')['default']
    IconCodiconDebugStop: typeof import('~icons/codicon/debug-stop')['default']
    Test: typeof import('./src/components/Test.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanProgress: typeof import('vant/es')['Progress']
  }
}
